services:
  mero_db:
      image: postgres:17
      container_name: mero_db
      env_file:
        - .env
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      volumes:
        - ./mero-db/sql:/docker-entrypoint-initdb.d
      networks:
        - mero_net
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    networks:
      - auth_net
      - backend_net

  event-service:
    build:
      context: ./event-service
    container_name: event-service
    ports:
      - "8002:8000"
    networks:
      - event_net
      - backend_net
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - event-service
    networks:
      - backend_net

networks:
  auth_net:
    driver: bridge
  event_net:
    driver: bridge
  mero_net:
    driver: bridge
  backend_net:
    driver: bridge